// General HTML/CSS study dataset. Cards: [topic, question, answer]
const TOPICS = ["HTML Basics","Semantic HTML","Text & Links","Images & Media","Lists & Tables","Forms","CSS Basics","CSS Selectors","Box Model","Layout","Responsive Design","Accessibility"];

const CARDS = [
  ["HTML Basics","What does HTML stand for?","HyperText Markup Language."],
  ["HTML Basics","What is HTML used for?","Structuring the content and meaning of web pages."],
  ["HTML Basics","What is an HTML element?","An HTML element is usually an opening tag, content, and a closing tag."],
  ["HTML Basics","What is an HTML attribute?","Extra information placed in an element's opening tag, such as `class` or `href`."],
  ["HTML Basics","What is the purpose of `<!DOCTYPE html>`?","It tells the browser to use modern HTML standards mode."],
  ["HTML Basics","What is the root element of an HTML document?","`<html>`."],
  ["HTML Basics","Where does metadata normally go?","Inside `<head>`."],
  ["HTML Basics","Where does visible page content normally go?","Inside `<body>`."],
  ["HTML Basics","What tag sets the browser tab title?","`<title>`."],
  ["HTML Basics","Why should HTML be properly nested?","Proper nesting makes the document structure predictable and easier for browsers and assistive technology to interpret."],
  ["Semantic HTML","What is semantic HTML?","HTML that uses elements according to their meaning and purpose."],
  ["Semantic HTML","What is `<header>` commonly used for?","Introductory content for a page or section, such as a heading or navigation."],
  ["Semantic HTML","What is `<nav>` used for?","A section containing major navigation links."],
  ["Semantic HTML","What is `<main>` used for?","The primary content of the page."],
  ["Semantic HTML","What is `<section>` used for?","A thematically grouped section of content, usually with a heading."],
  ["Semantic HTML","What is `<article>` used for?","A self-contained piece of content that could stand on its own."],
  ["Semantic HTML","What is `<aside>` used for?","Related or complementary content, such as a sidebar."],
  ["Semantic HTML","What is `<footer>` commonly used for?","Footer information such as copyright, contact information, or related links."],
  ["Semantic HTML","Why is semantic HTML useful?","It improves structure, accessibility, maintainability, and can help search engines understand content."],
  ["Semantic HTML","What should usually be used for the main page heading?","`<h1>`."],
  ["Text & Links","Which tag creates a paragraph?","`<p>`."],
  ["Text & Links","What are the heading elements?","`<h1>` through `<h6>`."],
  ["Text & Links","Which element indicates strong importance?","`<strong>`."],
  ["Text & Links","Which element indicates emphasis?","`<em>`."],
  ["Text & Links","Which element creates a line break?","`<br>`."],
  ["Text & Links","Which element creates a hyperlink?","`<a>`."],
  ["Text & Links","Which attribute gives an anchor its destination?","`href`."],
  ["Text & Links","What is a relative URL?","A URL that describes a location relative to the current page or site."],
  ["Text & Links","What is an absolute URL?","A complete URL that includes the protocol and domain, such as `https://example.com`."],
  ["Text & Links","What does `target=\"_blank\"` commonly do?","It asks the browser to open the linked page in a new browsing context, usually a new tab."],
  ["Images & Media","Which element displays an image?","`<img>`."],
  ["Images & Media","Which attribute specifies an image file?","`src`."],
  ["Images & Media","Why is `alt` important on images?","It provides a text alternative for users who cannot see the image and can appear if the image fails to load."],
  ["Images & Media","What makes useful alt text?","It briefly describes the meaningful content or purpose of the image."],
  ["Images & Media","How do you make an image a link?","Place the `<img>` element inside an `<a>` element."],
  ["Images & Media","Which element embeds audio?","`<audio>`."],
  ["Images & Media","Which element embeds video?","`<video>`."],
  ["Images & Media","What does the `controls` attribute do on audio or video?","It asks the browser to display built-in playback controls."],
  ["Images & Media","Why should image dimensions sometimes be specified?","They can help the browser reserve space and reduce layout shifting."],
  ["Images & Media","What is a relative image path?","A path such as `images/photo.jpg` that is resolved relative to the current document."],
  ["Lists & Tables","Which element creates an unordered list?","`<ul>`."],
  ["Lists & Tables","Which element creates an ordered list?","`<ol>`."],
  ["Lists & Tables","Which element represents a list item?","`<li>`."],
  ["Lists & Tables","When should you use an ordered list?","When the order of the items matters."],
  ["Lists & Tables","Which element creates a table?","`<table>`."],
  ["Lists & Tables","What does `<tr>` represent?","A table row."],
  ["Lists & Tables","What does `<td>` represent?","A table data cell."],
  ["Lists & Tables","What does `<th>` represent?","A table header cell."],
  ["Lists & Tables","What does `colspan` do?","It makes a table cell span multiple columns."],
  ["Forms","Which element creates a form?","`<form>`."],
  ["Forms","Which element creates a single-line text input?","`<input type=\"text\">`."],
  ["Forms","What does the `name` attribute do on a form control?","It gives the submitted value a field name."],
  ["Forms","What is `<label>` used for?","It identifies a form control and provides an accessible text label."],
  ["Forms","How can a label be associated with an input?","Use the label's `for` attribute with the input's matching `id`."],
  ["Forms","Which input type is used for a checkbox?","`<input type=\"checkbox\">`."],
  ["Forms","Which input type is used for a radio button?","`<input type=\"radio\">`."],
  ["Forms","Which element creates a multi-line text field?","`<textarea>`."],
  ["Forms","Which element creates a dropdown list?","`<select>` with `<option>` elements."],
  ["Forms","What does the `required` attribute do?","It tells the browser that a form control must have a value before submission."],
  ["CSS Basics","What does CSS stand for?","Cascading Style Sheets."],
  ["CSS Basics","What is CSS used for?","Styling and laying out HTML content."],
  ["CSS Basics","How can CSS be added to a page?","With inline styles, an internal `<style>` block, or an external stylesheet."],
  ["CSS Basics","What is usually the best choice for styling multiple pages?","An external stylesheet."],
  ["CSS Basics","How do you link an external stylesheet?","Use `<link rel=\"stylesheet\" href=\"styles.css\">` inside `<head>`."],
  ["CSS Basics","What is a CSS declaration?","A property and value pair, such as `color: blue;`."],
  ["CSS Basics","What is a CSS property?","The characteristic being styled, such as `color` or `margin`."],
  ["CSS Basics","What is a CSS value?","The setting assigned to a property, such as `blue` or `20px`."],
  ["CSS Basics","How do you write a CSS comment?","`/* comment */`."],
  ["CSS Basics","What does `color` control in CSS?","The foreground text color."],
  ["CSS Basics","What does `background-color` control?","The background color of an element."],
  ["CSS Selectors","What is a type selector?","A selector that targets elements by tag name, such as `p`."],
  ["CSS Selectors","How do you select a class in CSS?","Use a period followed by the class name, such as `.card`."],
  ["CSS Selectors","How do you select an ID in CSS?","Use `#` followed by the ID, such as `#header`."],
  ["CSS Selectors","What does the universal selector `*` match?","All elements."],
  ["CSS Selectors","What does `p, h2` mean in CSS?","It selects both `p` and `h2` elements."],
  ["CSS Selectors","What does `.card p` select?","Paragraphs that are descendants of an element with class `card`."],
  ["CSS Selectors","What does `:hover` represent?","A pseudo-class for an element while the pointer is over it."],
  ["CSS Selectors","What does `:focus` represent?","An element that currently has keyboard or other focus."],
  ["CSS Selectors","What is CSS specificity?","A set of rules browsers use to decide which competing declaration has more weight."],
  ["CSS Selectors","Which generally has greater specificity: a class or an ID?","An ID selector generally has greater specificity than a class selector."],
  ["Box Model","What are the four parts of the CSS box model?","Content, padding, border, and margin."],
  ["Box Model","What does `padding` control?","Space between an element's content and its border."],
  ["Box Model","What does `margin` control?","Space outside an element's border."],
  ["Box Model","What does `border` control?","The line surrounding the padding and content area."],
  ["Box Model","What does `box-sizing: border-box` change?","It makes the declared width and height include the element's padding and border."],
  ["Box Model","What does `width` normally control?","The width of an element's content box, unless box sizing changes the calculation."],
  ["Box Model","What does `max-width` do?","It prevents an element from becoming wider than a specified maximum."],
  ["Box Model","What does `min-height` do?","It prevents an element from becoming shorter than a specified minimum height."],
  ["Layout","What does `display: block` generally mean?","The element participates as a block-level box and normally starts on a new line."],
  ["Layout","What does `display: inline` generally mean?","The element participates within the current line of text."],
  ["Layout","What does `display: inline-block` allow?","It behaves inline while still allowing width, height, and box-model sizing."],
  ["Layout","How do you turn an element into a flex container?","Set `display: flex`."],
  ["Layout","What is the default flex direction?","`row`."],
  ["Layout","What does `justify-content` control in flexbox?","Distribution or alignment along the main axis."],
  ["Layout","What does `align-items` control in flexbox?","Alignment of flex items along the cross axis."],
  ["Layout","What does `gap` do in flexbox or grid?","Adds space between items without needing margins on each item."],
  ["Layout","What does `flex-wrap: wrap` allow?","Flex items can move onto additional lines when needed."],
  ["Layout","What is CSS Grid designed for?","Two-dimensional layout using rows and columns."],
  ["Layout","How do you make a grid container?","Set `display: grid`."],
  ["Responsive Design","What is responsive web design?","Designing pages so they adapt to different screen sizes and devices."],
  ["Responsive Design","What is a media query?","A CSS rule that applies styles when conditions such as viewport width are met."],
  ["Responsive Design","What does `@media` start?","A CSS media query."],
  ["Responsive Design","Why is the viewport meta tag useful?","It helps mobile browsers size the page to the device viewport correctly."],
  ["Responsive Design","What does `width: 100%` commonly do?","Makes an element use the available width of its containing block, subject to other constraints."],
  ["Responsive Design","Why use `max-width` on readable content?","It can prevent lines from becoming excessively wide and improve readability."],
  ["Accessibility","What is web accessibility?","Designing websites so people with a wide range of abilities can use them."],
  ["Accessibility","Why should form controls have labels?","Labels make controls easier to understand and use, especially with assistive technology."],
  ["Accessibility","Why is keyboard accessibility important?","Some users navigate without a mouse, so interactive controls should be reachable and usable by keyboard."],
  ["Accessibility","Why should color not be the only way to communicate information?","Users who cannot distinguish certain colors may otherwise miss important information."],
  ["Accessibility","What is a good heading structure?","Use headings in a logical hierarchy that reflects the page's content structure."],
  ["Accessibility","What is the purpose of the `lang` attribute on `<html>`?","It tells browsers and assistive technologies the primary language of the document."],
];

// Hand-written multiple-choice questions.
const QUIZ = [];

// Searchable review notes.
const OVERVIEW = TOPICS.map(t => [t, t, CARDS.filter(c => c[0] === t).slice(0, 8).map(c => `${c[1]} ${c[2]}`)]);